#!/bin/sh /etc/rc.common

START=97

start() {
        #sleep 5
         #. /etc/profile
         #echo $PATH
        /usr/bin/python /root/scripts/CouchPotatoServer/CouchPotato.py --quiet --daemon --pid_file=/tmp/couchpotato.pid --data_dir=/root/.couchpotato
        # commands to launch application
}

stop() {
kill -9 $(cat /tmp/couchpotato.pid)
kill -9 $(ps |grep Couch | awk '{print $1}' |head -n 1)
rm /tmp/couchpotato.pid
}
